# .github/workflows/pylint.yml

name: Pylint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        # The following line assumes all your runtime dependencies are in 'src/vista-api-backend'
        # Adjust the path if your requirements.txt is elsewhere.
        if [ -f src/vista-api-backend/requirements.txt ]; then pip install -r src/vista-api-backend/requirements.txt; fi
    - name: Analysing the code with pylint
      # Adjust the path to lint all relevant Python files.
      # The command below targets the 'app' directory inside 'src/vista-api-backend'.
      run: |
        pylint $(find src/vista-api-backend/app -name "*.py")
